/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gsl4j_roots_RealRoot */

#ifndef _Included_org_gsl4j_roots_RealRoot
#define _Included_org_gsl4j_roots_RealRoot
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gsl4j_roots_RealRoot
 * Method:    func
 * Signature: (Lorg/gsl4j/roots/RealRootFunction;D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_roots_RealRoot_func
  (JNIEnv *, jclass, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
